/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Gestion_des_centres;
  GtkWidget *authentification;
  GtkWidget *Menu_principal;
  GtkWidget *ajout_centre;
  GtkWidget *modifier_centre;
  GtkWidget *supprimer;
  GtkWidget *Rechercher_un_centre;
  GtkWidget *inscription;
  GtkWidget *selection;
  GtkWidget *authentification__entraineur;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Gestion_des_centres = create_Gestion_des_centres ();
  gtk_widget_show (Gestion_des_centres);
  authentification = create_authentification ();
  gtk_widget_show (authentification);
  Menu_principal = create_Menu_principal ();
  gtk_widget_show (Menu_principal);
  ajout_centre = create_ajout_centre ();
  gtk_widget_show (ajout_centre);
  modifier_centre = create_modifier_centre ();
  gtk_widget_show (modifier_centre);
  supprimer = create_supprimer ();
  gtk_widget_show (supprimer);
  Rechercher_un_centre = create_Rechercher_un_centre ();
  gtk_widget_show (Rechercher_un_centre);
  inscription = create_inscription ();
  gtk_widget_show (inscription);
  selection = create_selection ();
  gtk_widget_show (selection);
  authentification__entraineur = create_authentification__entraineur ();
  gtk_widget_show (authentification__entraineur);

  gtk_main ();
  return 0;
}

